import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
  site: 'https://onebasehealth.com',
  integrations: [sitemap()],
  vite: { plugins: [tailwindcss()] },
  redirects: {
    // Shopify → new
    '/collections/chambers': '/products/hbot',
    '/collections/red-lights': '/products/red-light',
    '/collections/sauna-1': '/products/sauna',
    '/collections/cold-therapy': '/products/cold-therapy',
    '/collections/contrast-therapy-heat-and-ice': '/products',
    '/collections/replacement-parts': '/parts',
    '/products/airfit-chamber': '/products/hbot/airfit',
    '/products/hyperbaric-oxygen-chamber-airflex': '/products/hbot/airflex',
    '/products/airform-chamber': '/products/hbot/airform',
    '/products/ice-vault-commercial-cold-therapy-room': '/products/cold-therapy/icevault',
    '/products/yakisugi-infrared-sauna': '/products/sauna/yakisugi',
    '/products/hemlock-4-person-sauna': '/products/sauna/hemlock',
    '/products/red-light-panel': '/products/red-light/lightpanel',
    '/products/red-light-panels': '/products/red-light/lightpanel',
    '/products/light-bed': '/products/red-light/lightbed',
    '/pages/our-story': '/about',
    '/pages/onebase-team': '/about',
    '/pages/contact': '/contact',
    '/pages/request-for-quote': '/contact',
    '/pages/for-businesses': '/solutions',
    '/pages/software-app': '/software',
    '/pages/software-roi': '/software',
    '/pages/retention-software': '/software',
    '/pages/airsuite': '/products/hbot/airsuite',
    '/pages/articles': '/blog',
    '/pages/warranty-policy-1': '/policies/warranty',
    '/pages/refunds-and-returns-policy': '/policies/returns',
    '/pages/privacy-policy': '/policies/privacy',
    '/pages/terms-of-use': '/policies/terms',
    '/blogs/education': '/blog',
    '/blogs/news': '/blog',
    '/blogs/red-light': '/blog',
    '/blogs/contrast-therapy': '/blog',
    '/blogs/science-research': '/blog',
    // Lovable (business.) slugs → new
    '/products/hbot-airfit': '/products/hbot/airfit',
    '/products/hbot-airflex': '/products/hbot/airflex',
    '/products/hbot-airform': '/products/hbot/airform',
    '/products/hbot-airsuite': '/products/hbot/airsuite',
    '/products/icevault': '/products/cold-therapy/icevault',
    '/products/lightpanel': '/products/red-light/lightpanel',
    '/products/lightbed': '/products/red-light/lightbed',
    '/products/infrared-sauna-yakisugi': '/products/sauna/yakisugi',
    '/products/infrared-sauna-hemlock': '/products/sauna/hemlock',
    '/refunds-and-returns': '/policies/returns',
    '/warranty-policy': '/policies/warranty',
    '/privacy-policy': '/policies/privacy',
    '/cookie-policy': '/policies/cookies',
  },
});
